### ISSUE TITLE
io.elementary.terminal.settings Change Alpha on RGBA Background won't Transparent

### ISSUE THREAD

**Issue by imbagila** [elementary/terminal#303]
I wanna make my terminal become transparent by typing in terminal like this:
`gsettings set io.elementary.terminal.settings background 'rgba(37, 46, 50, 0.5)'`
But even I change the alpha into 0, it will not become transparent. Is this a bug or I just doing wrong steps?

I'm using Elementary 5.0 Juno

**Comment by jeremypw** [comment]
Changing this setting using dconf-editor changes the opacity OK for me.  When I first tried your command it did not seem to work - but now it does.  Maybe mistyped the first time??

**Comment by imbagila** [comment]
Where you change the terminal opacity? I've changed the alpha value from RGBA background value using dconf-editor as well (in `io.elementary.terminal.settings`) but it's still not become transparent.

**Comment by milanplesa** [comment]
Done a fresh install 2 days ago. Also same issue. `gsettings set io.elementary.terminal.settings background 'rgba(37, 46, 50, 0.5)'` does nothing for me

**Comment by milanplesa** [comment]
Update: when terminal is maximized in is not transparent, but when it is not maximized it is transparent. Is this behaviour intentionally made and if so how can I change it?

**Comment by ukrdev** [comment]
Still not fixed? I have the same problem.
When you expand the full screen transparency disappears.

**Comment by casperfrx** [comment]
Interested in this one as well. I like to keep the transparency, even when docking to the left, right or fullscreen. Should be an easy to implement switchable option.

**Comment by casperfrx** [comment]
Found it. It's not switchable because it's hardcoded in the css that maximized and tiled isn't transparent.

`
.terminal-window.background {
    background-color: transparent;
}

.terminal-window.background.maximized,
.terminal-window.background.tiled {
    background-color: #000;
}
`

[Terminal CSS](https://github.com/elementary/terminal/blob/70ea668085ccb20072b982c0569cdddc52c2c8da/data/Application.css)

**Comment by milanplesa** [comment]
@danrabbit as you can see there is interest into changing this behaviour. As I could see current behaviour is intentional so I was wondering if changing this behaviour is a option?

**Comment by casperfrx** [comment]
+1, seems like an easy interface option.

**Comment by EmiSan1998** [comment]
I'm interested too, I hope to get the chance to set terminal transparent on fullscreen.

**Comment by milanplesa** [comment]
@cassidyjames can we do something about this issue please?

**Comment by cassidyjames** [comment]
Going opaque on maximize is intentional because it fixes some UI issues but also because if the Terminal is maximized, it's likely users are focusing on that content. We want to increase the contrast to make it easier to read and focus.

**Comment by casperfrx** [comment]
@cassidyjames Sorry I find that a rather easy way out. It is not up to me to decide but why not let the user choose whether or not to increase the contrast if it is maximized? I personally love the seethrough effect, just as much windowed as maximized so I would like this option. It could be opaque on default but the choice is a logical one, moreso because the transparancy level itself is customizable that it seems illogical not to allow this maximized as well.

I am interested in the UI issues it would cause as well.

**Comment by milanplesa** [comment]
I would also like to have transparent terminal on maximized by default or at lease an option. From to comment of this issue I'm not in minority. @cassidyjames is there an setting/option/file/workaround that I can currently modify/do to make my terminal transparent on maximized state?

**Comment by milanplesa** [comment]
For all those who are interested how to do a **WORKAROUND** 

- create file ~/.config/gtk-3.0/gtk.css
- add following code to the gtk.css
`.terminal-window.background.maximized,
.terminal-window.background.tiled {
    background-color: transparent;
}
`
- run "killall io.elementary.terminal"
- start terminal again
