### ISSUE TITLE
"Open in > Terminal" launches Terminal with two identical tabs

### ISSUE THREAD

**Issue by sprite-1** [elementary/terminal#356]
When i rght click in a folder in the Files app and choose Open n > Terminal, it launches Terminal with the folder path but with an additional duplicate tab.

**Comment by jeremypw** [comment]
If you have previously opened the same folder, and if restore tabs is on, then it seems to be restoring that folder *and* opening a new tab with the same folder. If you keep launching the same folder from Files, closing terminal in between, then each time you get one more duplicate.

**Comment by jeremypw** [comment]
I guess the correct behaviour is to neither restore or save tabs when launched from Files?

**Comment by sprite-1** [comment]
> If you have previously opened the same folder, and if restore tabs is on

I have that option disabled though, unless you're talking about something else

![image](https://user-images.githubusercontent.com/33685433/51992084-572b1f80-24e7-11e9-9432-9b056208eb68.png)

**Comment by jeremypw** [comment]
You are right - you still get duplicate tabs.  But you do not get ever increasing number of duplicates on repeated opening of the same folder.

**Comment by sprite-1** [comment]
Yeah, when I do Open in > Terminal, it doesn't add 2 new tabs to the existing Terminal window, just 1

**Comment by jeremypw** [comment]
I think this might be a duplicate of #245 - in which case there is a PR already awaiting approval to fix this.

**Comment by sharifzadesina** [comment]
Hey developers, any fix for this?
Bugs like this should be fixed without any delay.

**Comment by lxmcf** [comment]
I have attached an image showing an easy way to replicate this issue if it is any help

![Screen record from 2020-01-01 17 59 32](https://user-images.githubusercontent.com/29278620/71638917-d52c1380-2cc0-11ea-8a0f-5097d52f521f.gif)

**Comment by jeremypw** [comment]
The linked PR fixes the original issue (Open in Terminal from Files), but for some reason does not fix the issue with the example shell script above.  I will look into it.

**Comment by victorodg** [comment]
I'm having this problem..
