### ISSUE TITLE
No tab or empty window on remote start

### ISSUE THREAD

**Issue by robn** [elementary/terminal#453]
Since #265 was merged, when running the `io.elementary.terminal` binary directly to open a new window or tab, results in either an empty (no widget) window, or no new tab.

I've been seeing this since current master (0732d752) but bisected it to 2df52a9c.

#### Tabs:
1. close all terminal instances
2. run `io.elementary.terminal`; new terminal window starts
3. run `io.elementary.terminal`
4. nothing happens

#### Windows:
1. close all terminal instances
2. run `io.elementary.terminal`; new terminal window starts
3. run `io.elementary.terminal -n`
4. empty window (no widgets) appears

The workaround I'm using is:

```diff
diff --git src/MainWindow.vala src/MainWindow.vala
index fffddf4e..8c4a952b 100644
--- src/MainWindow.vala
+++ src/MainWindow.vala
@@ -282,7 +282,7 @@ namespace Terminal {
                 if (command != null) {
                     location = Terminal.Application.working_directory ?? Environment.get_current_dir ();
                 } else {
-                    /* Do not add spurious new tab */
+                    new_tab("");
                     return;
                 }
             } else {
```

However, there does result in a new tab + restored tabs, so isn't a good general fix. I'm not entirely sure what this code is trying to test for (it seems to assume that an empty directory is only for initial startup, not remote start) so I don't have anything better right now. I'll have a proper go at it tonight if you don't get there first; right now I just need something to get me through my work day.

**Comment by deyvisonrocha** [comment]
See #444

**Comment by robn** [comment]
> See #444

For?

**Comment by robn** [comment]
Just so we're clear, when I say "empty window" I mean:

![Screenshot from 2020-01-09 21 56 45@2x](https://user-images.githubusercontent.com/130670/72061979-00e77300-332b-11ea-8680-d221268f0dd7.png)

**Comment by jeremypw** [comment]
Hmm, don't know how that was missed - will fix asap.

**Comment by jeremypw** [comment]
Strange - a tab is being added but not showing for some reason ...

**Comment by jeremypw** [comment]
I have pushed a proposed fix - if you are able to test for regressions I would be grateful.

**Comment by robn** [comment]
@jeremypw #456 works for the new window case (running with `-n`), and I will use it today. It doesn't seem to fix the new tab case - running `io.elementary.terminal` in a terminal does not open a new tab (doesn't bother me, but is a regression I think).

**Comment by jeremypw** [comment]
Thanks. I think that running `io.elementary.terminal` with no flags is meant to just present an existing window if there is one. This would be in line with the behaviour of other elementary apps e.g. Files, Code

**Comment by robn** [comment]
Cool, I just wasn't sure. Cheers for the quick fix.
