### ISSUE TITLE
Unable to install terminal from appcenter on pinebook pro

### ISSUE THREAD

**Issue by popey** [elementary/terminal#531]
## Prerequisites
- [X] I have searched open and closed issues for duplicates.

## Describe the bug
Unable to install Terminal on elementary OS 6.0 on the PineBook Pro (arm).

### To Reproduce
1. Open App Center
2. Search for Terminal
3. Attempt to install Terminal

### Expected behavior
Terminal would install.

### Screenshots or screen recordings

![Screenshot from 2020-08-13 11-06-24](https://user-images.githubusercontent.com/1841272/90127905-7f8b0f80-dd55-11ea-9e1d-fd4e29839c24.png)

### Logs
```
The following packages have unmet dependencies:
  pantheon-terminal: Depends: io.elementary.terminal but it is not going to be installed
```

## Platform Information

![Screenshot from 2020-08-13 11-06-24](https://user-images.githubusercontent.com/1841272/90128118-d85aa800-dd55-11ea-8057-01c8ea461366.png)
![Screenshot from 2020-08-13 11-11-42](https://user-images.githubusercontent.com/1841272/90128121-d98bd500-dd55-11ea-8812-d8a4695376c4.png)

- [ ] I'm using the latest version from git that I've manually compiled
- [ ] I'm using the latest released stable version
- [X] I'm using an early-access pre-release arm build

**Comment by popey** [comment]
Same problem on the daily x86 iso also. `elementaryos-6.0-daily.20200813.iso`

![Screenshot from 2020-08-13 16-14-33](https://user-images.githubusercontent.com/1841272/90152843-2c7a8200-dd80-11ea-905f-200506296285.png)

**Comment by danrabbit** [comment]
I updated Seeds, so this should be fixed for future images. But according to @tintou for the upgrade to work:

> If you want the RDNN changes to work you have to
bump io.elementary.foo version to X.Y.Z+1
```
Replaces: foo (<< X.Y.Z)
Breaks: foo (<< X.Y.Z)
```
>What is missing is the (<< X.Y.Z)  everywhere and a version bump because if you don't specify the version it can't upgrade as it would break foo on any version

**Comment by ChildishGiant** [comment]
I'm still getting this on a daily build although it's worth noting that the terminal is already ready to use on install, although not marked as installed on the appcenter

* elementaryos-6.0-daily.20210624
* ThinkPad T460 
*  Kernel: 5.8.0-59-generic
